version: '3.8'

services:

  photobook-db:
    image: postgres
    container_name: postgres-db-dev
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: photobookdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: passwrd
    ports:
      - 5432:5432
    networks:
      - app-photobook-network

  photobook-pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin-dev
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: app2@photobook.pe
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - 80:80
    networks:
      - app-photobook-network

networks:
  app-photobook-network:
