type LoginAuthResponse {
  user: User!
  access_token: String!
}

type RegisterAuthResponse {
  message: String
  error: Boolean!
  user: User
}

input RegisterUserDto {
  name: String!
  lastname: String!
  email: EmailAddress!
  password: String!
}
