type LoginAuthResponse {
  user: User
  access_token: String
  message: String
  error: Boolean!
}

type RegisterAuthResponse {
  message: String
  error: Boolean!
  user: User
}

input RegisterUserDto {
  name: String!
  lastname: String!
  email: EmailAddress!
  password: String!
}


input LoginUserDto {
  email: EmailAddress!
  password: String!
}
