type Mutation {
  login(dto: LoginUserDto!): LoginAuthResponse
  register(dto: RegisterUserDto!): RegisterAuthResponse

  createPost(dto: CreatePostDto!): CreatePostResponse
  editPost(dto: EditPostDto!): EditPostResponse
}
