type User {
  user_id: ID!
  email: String!
  name: String!
  lastname: String!
  about: String
  photo_id: String
  roles: [Role]!
  username: String!
}

type Role {
  role_id: Int!
  name: String!
}
